Added Make Firmware function, fixed missing /mnt/cf directory

diff --git a/alixdev b/alixdev
--- a/alixdev
+++ b/alixdev
@@ -1,12 +1,18 @@
 #!/bin/bash
 
-ROOTDIR=${PWD}
-
+# These need to be configured for the desired environment
 BUILDROOTVER=2011.05
 KERNELVER=2.6.39.4
 UNIONFSVER=2.5.10
+
+
+# Helper Vars
+VERSION=`cat buildver`
+ROOTDIR=${PWD}
 UNIONFSPATCH=unionfs-${UNIONFSVER}_for_${KERNELVER}.diff
 BUILDROOTSRC=${ROOTDIR}/src/buildroot-${BUILDROOTVER}.tar.bz2
+IMAGES=${ROOTDIR}/buildroot/output/images
+TMPDIR=${ROOTDIR}/tmp
 
 checklink()
 {
@@ -40,6 +46,20 @@ makecf()
     rm -rf vm/mnt/
 }
 
+makefw()
+{
+    mkdir -p ${TMPDIR}/firmware
+    if [ -f ${IMAGES}/bzImage ] && [ -f ${IMAGES}/rootfs.initramfs ]
+    then
+        cp ${IMAGES}/bzImage ${IMAGES}/rootfs.initramfs ${TMPDIR}/firmware
+        cp ${ROOTDIR}/cf/syslinux.cfg ${TMPDIR}/firmware
+        cd ${TMPDIR}/firmware
+        tar cvfz ${ROOTDIR}/alixdev-bin-0.${VERSION}.tgz *
+    else
+        echo "Error, missing source file"
+        exit 1
+    fi
+}
 
 case $1 in
 	get)
@@ -77,9 +97,9 @@ case $1 in
 		;;
 	patch)
 		PATCH=${ROOTDIR}/src/unionfs-${UNIONFSVER}_for_${KERNELVER}.diff.gz
-		if [ ! -f $PATCH ]
+		if [ ! -f ${PATCH} ]
 		then
-			echo "Cannot find $PATCH"
+			echo "Cannot find ${PATCH}"
 			exit 1
 		else
 			cd ${ROOTDIR}/buildroot/output/build/linux-${KERNELVER}
@@ -87,10 +107,10 @@ case $1 in
 		fi
 		;;
 	build)
-		ver=`cat buildver`
-		let ver+=1
-		echo -e "\nALIXDEV Build ${ver}\n" > skeleton/etc/issue
-		echo $ver > buildver
+		let VERSION+=1
+		echo -e "\nALIXDEV Build ${VERSION}\n" > ${ROOTDIR}/skeleton/etc/issue
+        cp ${ROOTDIR}/skeleton/etc/issue ${ROOTDIR}/buildroot/output/target/etc/
+		echo ${VERSION} > buildver
         if [ ! -f ${ROOTDIR}/buildroot/.config ]
         then
             echo "Config not found, will copy..."
@@ -98,12 +118,14 @@ case $1 in
         fi
 		(cd buildroot ; make all | tee ../build.log)
 		;;
+    makefw)
+        makefw
+        ;;
 	runvm)
         if [ ! -f vm/cf.img ]
         then
             makecf
         fi
-		IMAGES=${ROOTDIR}/buildroot/output/images
 		qemu -cpu pentium -kernel ${IMAGES}/bzImage -initrd ${IMAGES}/rootfs.initramfs -serial stdio -net nic,vlan=1 -net user,vlan=1 -hda ${ROOTDIR}/vm/cf.img
 		;;
 	*)
